# Generated by Django 4.0.5 on 2022-06-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('user', '0002_adminuser_employeeuser_hruser_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attrition_type',
            field=models.CharField(blank=True, choices=[('VOLUNTARY', 'Voluntary'), ('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('DEATH', 'Death'), ('RETIREMENT', 'Retirement')], default='VOLUNTARY', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_hire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='effective_resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_day_of_work',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reason_for_separation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rehire_eligibility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resignation_letter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
