# Generated by Django 4.0.5 on 2022-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_bamboo_hr_active_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='attrition_type',
            field=models.CharField(blank=True, choices=[('NOT_APPLICABLE', 'Not_Applicable'), ('VOLUNTARY', 'Voluntary'), ('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('DEATH', 'Death'), ('RETIREMENT', 'Retirement')], default='NOT_APPLICABLE', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin'), ('HR', 'Hr'), ('PARTNER', 'Partner')], default='EMPLOYEE', max_length=50),
        ),
    ]
